# Generated by Django 4.0.3 on 2022-05-20 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='delivery',
            name='active_arcs',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='depo_coords',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DeliveryVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_vehicles', to='api.delivery')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.vehicle')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.deliveryvehicle'),
        ),
    ]
