# Generated by Django 4.0.3 on 2022-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_number',
            field=models.CharField(default='195700004567004', max_length=15),
            preserve_default=False,
        ),
    ]
