# Generated by Django 4.0.3 on 2022-05-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delivery_delivery_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery',
            new_name='deliveryVehicle',
        ),
    ]
