# Generated by Django 4.0.3 on 2022-05-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_delivery_order_deliveryvehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-10-12 11:13'),
            preserve_default=False,
        ),
    ]
