# Generated by Django 4.0.3 on 2022-05-31 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delivery_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='active_arcs',
        ),
        migrations.AddField(
            model_name='deliveryvehicle',
            name='active_arcs',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryvehicle',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_vehicles', to='api.driver'),
        ),
        migrations.AlterField(
            model_name='deliveryvehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_vehicles', to='api.vehicle'),
        ),
    ]
