# Generated by Django 4.0.3 on 2022-06-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_delivery_active_arcs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='depo_coords',
            field=models.CharField(default='0.1378, 35.3944', max_length=150),
        ),
    ]
