# Generated by Django 4.0.3 on 2022-04-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_clients', models.PositiveSmallIntegerField()),
                ('vehicle_capacity', models.FloatField()),
            ],
        ),
    ]
